FROM node:18-alpine

ENV API_URL=http://backend-host:5000/api

# Set working directory
WORKDIR /app

# Copy package files first (for caching)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy rest of  code
COPY . .

# Expose port (change if needed)
# EXPOSE 3000

# Start app
CMD ["npm", "run", "dev"]
